name: Drive test

on:
  workflow_dispatch:
    inputs:
      drive_url:
        description: 'Google Drive file or folder URL'
        required: true
        type: string

jobs:
  test-drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Run drive test
        env:
          IA_EMAIL: ${{ vars.IA_EMAIL }}
          IA_PASSWORD: ${{ vars.IA_PASSWORD }}
        run: |
          iadrive "${{ github.event.inputs.drive_url }}"
